# Generated by Django 3.1.7 on 2021-05-16 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20210514_1741'),
        ('coupon', '0003_auto_20210511_1321'),
    ]

    operations = [
    ]
