# Generated by Django 3.1.7 on 2021-04-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210429_1959'),
        ('order', '0002_auto_20210429_1359'),
    ]

    operations = [
    ]
